title:  'Shared Tasks in the Digital Humanities'
tagline:      'Systematic Analysis of Narrative Texts through Annotation'
description:  'Initiative for Shared Tasks in the Digital Humanities'
version:      1.1.1
author:
  name:       ''
  email:      ''
permalink:    pretty
excerpt_separator: <!--more-->
shcolor: blue
