title:  'Shared Tasks in the Digital Humanities'
tagline:      'Shared Tasks in the Digital Humanities'
description:  'A Shared Task for a Shared Goal - Systematic Annotation of Literary Texts'
version:      1.1.1
author:
  name:       ''
  email:      ''
permalink:    pretty
excerpt_separator: <!--more-->
shcolor: blue