title:  'Shared Tasks in the Digital Humanities'
tagline:      'Phase 1: Systematic Analyis of Narrative Texts through Annotation (SANTA)'
description:  'Initiative for Shared Tasks in the Digital Humanities'
version:      1.1.1
author:
  name:       ''
  email:      ''
permalink:    pretty
excerpt_separator: <!--more-->
shcolor: blue