title:
tagline:      'Shared Tasks in the Digital Humanities'
description:  'Shared Tasks in the Digital Humanities'
version:      1.1.1
author:
  name:       ''
  email:      ''
permalink:    pretty
